### ISSUE TITLE
Get travis working or switch to another CI system that works with github

### ISSUE THREAD

**Issue by BryanCrotaz** [shaunc/ember-grid#26]
Could you investigate?

**Comment by shaunc** [comment]
I turned travis off because ember-collection doesn't build with phantomjs, as it uses requestAnimationFrame. I tried a polyfill but it didn't work. I also opened an issue with ember-collection.

We may want to try circle-ci ... also we may move away from ember-collection. I'm going to try to improve scrolling performance this weekend -- hopefully will be decisive one way or another.

I'll change title to track need for CI.

How did you're talk go?

**Comment by shaunc** [comment]
Turned travis back on as we've dropped ember-collection
